INSERT INTO satislar (satis_tarihi, musteri_adi, urun_tipi_id, tutar, para_birimi, sube_id) VALUES
(CAST('01.01.2026' AS DATE), 'HANNAH LEWIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 330.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.01.2026' AS DATE), 'MICHELLE BELSKIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.01.2026' AS DATE), 'WILLIAM MR MCGIBBON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 672.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.01.2026' AS DATE), 'REBEKAH MCKINZIE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 790.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.01.2026' AS DATE), 'STEVE FOUST', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.01.2026' AS DATE), 'MARIA KAPPELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 380.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.01.2026' AS DATE), 'SHARON KAPPELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.01.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 825.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.01.2026' AS DATE), 'SUSAN VANNUCCI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.01.2026' AS DATE), 'VADNEY HANSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.01.2026' AS DATE), 'JAMES MULLINS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.01.2026' AS DATE), 'CHRISTINE MORRIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 878.8, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.01.2026' AS DATE), 'ROBIN SANFORD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 999.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.01.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.01.2026' AS DATE), 'ROBERT A SHOULTS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 849.29, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.01.2026' AS DATE), 'RUTH HEILMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 880.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.01.2026' AS DATE), 'CECELIA EHRET', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 920.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.01.2026' AS DATE), 'WILLIAM CHESHIRE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 473.85, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.01.2026' AS DATE), 'JACOB STOREY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.01.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.01.2026' AS DATE), 'JACKIE AOUGHSTEN -ANNE HUFF', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.01.2026' AS DATE), 'CAMILLE MA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('06.02.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 70.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.02.2026' AS DATE), 'THOMULLER FRANZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 943.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.02.2026' AS DATE), 'BERNHARD SCHABER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 943.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.02.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.02.2026' AS DATE), 'NASTASSJA GAUDET-STEPHENIE MAYBERRY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.02.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.03.2026' AS DATE), 'ERIN MCNEILL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.03.2026' AS DATE), 'JAMES CRUMBLEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.03.2026' AS DATE), 'PHILLIP ZEGELBONE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.03.2026' AS DATE), 'SUSAN SEE', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 675.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.03.2026' AS DATE), 'KYUNGRAN KOH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 416.38, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.03.2026' AS DATE), 'HUITZU CHOU', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 250.72, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.03.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 103.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.03.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 75.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.03.2026' AS DATE), 'TERENCE FITZGERALD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.03.2026' AS DATE), 'JANET THOMPSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('26.03.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 319.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.03.2026' AS DATE), 'ROBERT BANFIELD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.03.2026' AS DATE), 'GREGORY GABRIELE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 450.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.03.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 190.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.03.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 65.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.03.2026' AS DATE), 'SCHROTH WALTER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 825.26, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.03.2026' AS DATE), 'SCHROTH WALTER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 858.64, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.03.2026' AS DATE), 'GRAHAM PITT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 240.5, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.03.2026' AS DATE), 'GRAHAM PITT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 240.5, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'JON AUTHIER-KELLY AUTHIER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 849.26, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'JON AUTHIER-KELLY AUTHIER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 849.26, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'CYNTHIA PARULAN COLFER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'STEPHEN GALLAGHER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'TOBI MCGUIGAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'KATHRYN ARKIN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 847.22, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.04.2026' AS DATE), 'PATRICIA RICH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.04.2026' AS DATE), 'KELLIE EDWARDS-LINDA CODY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.93, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.04.2026' AS DATE), 'KELLIE EDWARDS-LINDA CODY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.93, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.04.2026' AS DATE), 'DENNIS YANCHYCKI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 797.74, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 32.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.04.2026' AS DATE), 'ROSENNE CUSICK', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('09.04.2026' AS DATE), 'GINA MARIE DESTAFNEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('09.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 675.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.04.2026' AS DATE), 'NANCY IVERSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.04.2026' AS DATE), 'NANCY IVERSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.04.2026' AS DATE), 'NANCY IVERSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.04.2026' AS DATE), 'NANCY IVERSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.04.2026' AS DATE), 'NANCY IVERSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 100.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 970.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'JOHN COLOMBO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'WAYNE BALDWIN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'JANET OLSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 540.83, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'JANET OLSEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 559.17, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'JOHN PRICKETT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 150.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 75.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.04.2026' AS DATE), 'JON D BELCHER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 85.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.04.2026' AS DATE), 'RICHARD DOSS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 833.33, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('21.04.2026' AS DATE), 'KALPANA PATEL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.04.2026' AS DATE), 'ALISON MISS EMERY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 877.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.04.2026' AS DATE), 'ROBERT MILLER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.04.2026' AS DATE), 'MARY MOORE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('27.04.2026' AS DATE), 'MARGARET REINHART', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 729.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 100.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.04.2026' AS DATE), 'CINDY NEWELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.04.2026' AS DATE), 'KAREN GATES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'DEBBIE ZIMEL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 200.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'NICHOLAS VERMETTE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 954.55, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'GERTRUDE L GREEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 256.29, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'BARBARA A GREENE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 305.23, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 165.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'JOSEPH EISEMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'PATRICK BOTBYL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'MARGARET EISEMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), 'KEVIN GALLAGHER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('29.04.2026' AS DATE), 'NANCY BROWN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.04.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 55.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.04.2026' AS DATE), 'JOSEPH ARTHUR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 450.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.04.2026' AS DATE), 'CYNTHIA A HARRAR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.04.2026' AS DATE), 'SUSAN MANNING', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 890.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.05.2026' AS DATE), 'KIMBERLY SMITH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 698.49, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.05.2026' AS DATE), 'TAYLOR SMITH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 544.55, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('01.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 185.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.05.2026' AS DATE), 'JOSHUA M BRONSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 195.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 820.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('02.05.2026' AS DATE), 'LAURA LANE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('02.05.2026' AS DATE), 'LINDA ROBBINS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 525.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.05.2026' AS DATE), 'CLAYBON JACKSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.05.2026' AS DATE), 'CLAIREMARIE TAYLOR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 720.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 160.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.05.2026' AS DATE), 'FRANCIS LOUBIER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 475.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.05.2026' AS DATE), 'CINDY NELSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('06.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 78.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 120.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.05.2026' AS DATE), 'YASSIR ELIAS KAKO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 161.37, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('06.05.2026' AS DATE), 'RONNIEL NITO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 375.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 126.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.05.2026' AS DATE), 'VICTORIA ANN KROPF', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'JOHN MOORE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 409.7, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'RAY UTZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'RUSSEL NEUDORF', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 845.81, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'DANIEL DAVIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 175.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 15.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'JOY WHITE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 150.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'TERRY WEINBERGER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), 'DWAINE P ESHELMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 176.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 130.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.05.2026' AS DATE), 'PETER MCGIRR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 679.5, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.05.2026' AS DATE), 'PETER MCGIRR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 679.5, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.05.2026' AS DATE), 'VIVIAN BALMEO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 85.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.05.2026' AS DATE), 'ANDOSHKA CASWILL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.05.2026' AS DATE), 'ABBY CUMBER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 204.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 100.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.05.2026' AS DATE), 'STACEY L GREGG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.05.2026' AS DATE), 'STACEY L GREGG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.05.2026' AS DATE), 'KAREN T BUTLER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.05.2026' AS DATE), 'ERIN GINSBURG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 115.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.05.2026' AS DATE), 'FATIMA AGCAOILI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 491.23, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.05.2026' AS DATE), 'FATIMA AGCAOILI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 508.77, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'BRYAN RANGEL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 520.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'YVETTE FOSSUM', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 457.63, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'RICHARD DAVIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 625.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'DIANE LYNCH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 105.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'AARON CALI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'GLENDA APOSTOL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 225.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.05.2026' AS DATE), 'PATRICIA SALZER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.05.2026' AS DATE), 'ALAN WILKINSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 694.99, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.05.2026' AS DATE), 'ALAN WILKINSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 838.06, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.05.2026' AS DATE), 'ALAN WILKINSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 877.12, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 14.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 65.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.05.2026' AS DATE), 'JODY QUILTY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 291.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 560.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('19.05.2026' AS DATE), 'MICHAEL SHARP', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 968.14, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('19.05.2026' AS DATE), 'CHRISTOPHER TOULSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 580.72, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('19.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 66.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 10.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), 'PATRICK S BIELENY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 910.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), 'PATRICK S BIELENY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 981.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 32.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 15.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 25.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 70.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 110.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), 'KAREN WATKINS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.05.2026' AS DATE), 'TIMOTY GAITHER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 820.51, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('20.05.2026' AS DATE), 'EMILY ARNOLD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('20.05.2026' AS DATE), 'SUSAN WALKER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 941.37, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('20.05.2026' AS DATE), 'CHRYSTAL MCARTHUR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('21.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 28.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 450.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 170.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 58.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.05.2026' AS DATE), 'CHRISTOPHER ROGERS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('26.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 210.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 80.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 10.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), 'MARICELIS RIVERA SANTOS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), 'DOMINGO RIVERA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 950.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 680.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('27.05.2026' AS DATE), 'CHRISTOPHER JANICH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 324.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.05.2026' AS DATE), 'DIANA RUBIANO-CIRILLO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.05.2026' AS DATE), 'MARIANO STO DOMINGO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 44.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.05.2026' AS DATE), 'JOHN BELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.05.2026' AS DATE), 'CHRISTINE BLAND FLAGG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 202.99, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.05.2026' AS DATE), 'LANDON PARKER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('28.05.2026' AS DATE), 'KASEY MOFFETT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('29.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 75.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), 'MICHAEL CURRY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), 'MICHAEL CURRY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), 'MICHAEL CURRY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), 'CAROLINA ROMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.05.2026' AS DATE), 'PHILLIP HUNTER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 734.69, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('30.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 65.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.05.2026' AS DATE), 'ANITA MCIVER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 536.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 78.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.05.2026' AS DATE), 'MICHAEL NOWACKI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 495.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.05.2026' AS DATE), 'CARLOS SANCHEZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 20.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.05.2026' AS DATE), 'ELIZABETH LEMASTER-CHRISTOPHER LEMASTER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 627.17, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('31.05.2026' AS DATE), 'SHARON L MOLINA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.05.2026' AS DATE), 'SHARON L MOLINA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 200.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 673.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('31.05.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.06.2026' AS DATE), 'BURKART KNOSPE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 537.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 95.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), 'JOHN METAXAS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 614.63, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.06.2026' AS DATE), 'TRUDY MAERZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 490.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.06.2026' AS DATE), 'LESLIE BARLOW', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 603.45, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.06.2026' AS DATE), 'FRANCISCO VARGAS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 245.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 63.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), 'MICHELLE COLLINS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 130.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('03.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 157.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 95.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.06.2026' AS DATE), 'JESSICA ELLYN SCHMIDT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('06.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 135.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.06.2026' AS DATE), 'FRED M WORSHAM', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 713.79, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('09.06.2026' AS DATE), 'BRAD VICKERS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 577.47, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.06.2026' AS DATE), 'FRANCE BONDOS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.06.2026' AS DATE), 'PAUL UGOLINI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.06.2026' AS DATE), 'ALLISON VAN HORN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 625.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 44.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.06.2026' AS DATE), 'MARIA GRANDE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 200.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.06.2026' AS DATE), 'MICHAEL CONGER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 480.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('12.06.2026' AS DATE), 'MEGAN DEHNE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 837.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.06.2026' AS DATE), 'JUDY GIESBRECHT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.06.2026' AS DATE), 'CARY GOLDSTEIN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 621.44, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.06.2026' AS DATE), 'MELEAH MONTGOMERY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.06.2026' AS DATE), 'CYNTHIA L CARROLL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.06.2026' AS DATE), 'CYNTHIA L CARROLL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 350.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'KRISTEN WEIDENFELLER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'KRISTEN WEIDENFELLER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 52.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 85.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'MARK CHAMBERS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'MICHELE IAIA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'GERALDINE C IAIA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'CANDACE DONATO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 250.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 70.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.06.2026' AS DATE), 'CAROL OKADA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 775.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 330.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.06.2026' AS DATE), 'JACK A BOBO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('17.06.2026' AS DATE), 'NORMA LOPEZ CASTA EDA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 648.65, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('17.06.2026' AS DATE), 'YADELENE BRASWELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 419.89, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'FREEDOM TRIPP', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 882.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'ADRIEN RUVALCABA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'TRACIE TOMAK', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 951.15, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'DIANA TURNER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'SAMMIE L ROBINSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'SUSAN E KING', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'ALAN MACLEAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 406.98, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.06.2026' AS DATE), 'ANDREW T DR DANIELS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 740.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 55.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), 'MELISSA LOYCE MEYERS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.06.2026' AS DATE), 'AMY COCHRAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.06.2026' AS DATE), 'EMMA CALNAN-CONOR CALNAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 630.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 10.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 100.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), 'SHANEKA ANDERSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 575.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), 'JENNIFER S STULL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 625.81, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 104.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 115.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'MATTHEW C MOENCH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 228.87, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'MATTHEW C MOENCH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 228.87, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'JESSICA ROWDEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 311.54, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'MELISSA HART', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 574.07, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'BONNI WANAMAKER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 333.86, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'JENIFER PAQUETTE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 676.77, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.06.2026' AS DATE), 'JASON FELLNER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 507.05, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 120.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 14.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.06.2026' AS DATE), 'JEANNE STINCHOMB', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 90.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 82.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.06.2026' AS DATE), 'MAUREEN C DALDON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 575.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('27.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 80.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.06.2026' AS DATE), 'MAXWELL HERNANDEZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 530.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.06.2026' AS DATE), 'AMANDA THOM', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 606.97, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('30.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 209.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.06.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 160.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.06.2026' AS DATE), 'RILEY E BLACKWELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.06.2026' AS DATE), 'CECILY ROMANOWSKI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.07.2026' AS DATE), 'CHRISTINA BACON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 337.84, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 57.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 80.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.07.2026' AS DATE), 'SHELBY BATES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 797.93, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('02.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 133.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('02.07.2026' AS DATE), 'SYDNEY SCHNEIDMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('06.07.2026' AS DATE), 'KEITH LANE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 620.69, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('06.07.2026' AS DATE), 'KEITH LANE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 579.31, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 6.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 42.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 180.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.07.2026' AS DATE), 'ASHLEY DONNA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('08.07.2026' AS DATE), 'CAROL YOUNG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 627.19, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.07.2026' AS DATE), 'CAROL YOUNG', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 558.06, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('08.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 55.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 111.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), 'JOHN GANNON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('09.07.2026' AS DATE), 'PAMELA J WILLIAMS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 285.23, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), 'JOHN A SHABAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 191.19, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), 'FAITH BIRD & MEGAN MASTERSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 65.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('09.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 880.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 80.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'M LOPEZ MARTINEZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 639.74, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 25.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'JONATHAN K MORSE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 42.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'ROBERT O SHEARER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'KAREN WHITHAM', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 664.1, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'KAREN WHITHAM', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 745.51, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 70.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.07.2026' AS DATE), 'LAUREL F EVERETT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), 'C COBSIGLIO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 620.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 5.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), 'JEREMY WITBECK', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 311.78, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.07.2026' AS DATE), 'JEREMY WITBECK', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 311.78, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 68.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 118.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 20.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.07.2026' AS DATE), 'NORMAN SIMITH', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('11.07.2026' AS DATE), 'ERIN VERONICA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'CHANTAL BROWN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 740.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'MIRNA MARON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'SHERRI CURTIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 414.55, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'SHERRI CURTIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 345.45, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 69.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'JULIE TOMLIN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 965.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 14.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'HEATHER R PERKINS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'SRIKANDANADARAJAH KANDASAMI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('14.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 73.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('14.07.2026' AS DATE), 'J POTTER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 55.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'CLAYTON MARAIST', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 367.77, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'CLAYTON MARAIST', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 441.32, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'CLAYTON MARAIST', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 441.32, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'RILEY GROSSE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 650.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'MARCIA M B GOMES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'ATANACIO GARCIA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'ATANACIO GARCIA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 239.02, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'JORGE SOSA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.07.2026' AS DATE), 'JORGE SOSA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 34.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 135.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.07.2026' AS DATE), 'ADRIAN RODRIGUEZ GALLARDO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('16.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 24.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 10.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('16.07.2026' AS DATE), 'CHASE CHAPMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.07.2026' AS DATE), 'AMARKYS BRITO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.07.2026' AS DATE), 'ANANIA RUFINO', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('21.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 114.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('21.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 100.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'JESSICA CHANEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 658.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'KRISTINE HOMANT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 408.19, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'JONATHAN JANDORF', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 596.25, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'JILLIY VELEZ', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'MORGAN HUFF', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 590.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('22.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 90.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 34.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'TARAN CARTER RUSSELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'JACOB L RUSSELL', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 5.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'CAROL TALLEY-GAUGE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 462.11, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('22.07.2026' AS DATE), 'ROXANNE FLORES MULLER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 850.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('23.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 90.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('23.07.2026' AS DATE), 'JANE B HUFFMAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.07.2026' AS DATE), 'ROBERT A KASUBA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 955.21, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('24.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.07.2026' AS DATE), 'NORINA SERRATURE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 709.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.07.2026' AS DATE), 'MARIE EVE DUPONT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 638.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.07.2026' AS DATE), 'CHRISTINE ELDREDGE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 427.15, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.07.2026' AS DATE), 'CLEO SAMPSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 467.44, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('25.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 22.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('25.07.2026' AS DATE), 'ALICIA BELLE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 710.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.07.2026' AS DATE), 'MIREYA GONZALES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 575.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('28.07.2026' AS DATE), 'ANTHONY PANOUSOPOULOS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 750.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.07.2026' AS DATE), 'ANTONIO NADAIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 276.66, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('29.07.2026' AS DATE), 'LUIZ BORGES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('29.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 60.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.07.2026' AS DATE), 'AMANDA HITI', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('29.07.2026' AS DATE), 'SHEILA MOORE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('30.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.07.2026' AS DATE), 'REBECCA REYNOLDS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 450.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('30.07.2026' AS DATE), 'KENNETH STANLEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 288.1, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('30.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 170.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.07.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('31.07.2026' AS DATE), 'OLIVER TER MAULEN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 352.11, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.08.2026' AS DATE), 'HOLLY L SCHWAB', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 500.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 7.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('01.08.2026' AS DATE), 'NATHALIE MANALIGOD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 30.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'JOHN L WRIGHT', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 210.63, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'PATRICIA DORAN', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 900.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'TIMOTY BOWSER', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 600.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'TRISHA FINEZA FORBES', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'CHERYL   BOURQUE', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 300.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('04.08.2026' AS DATE), 'TWINDALYNN HARRIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 275.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('05.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 14.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('05.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 119.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('05.08.2026' AS DATE), 'JULIA SIJKA', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 700.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('05.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 157.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('07.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 577.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.08.2026' AS DATE), 'JACOUELINE FLAHERTY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 552.98, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('07.08.2026' AS DATE), 'JACOUELINE FLAHERTY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 464.02, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('10.08.2026' AS DATE), 'SHARON MCDONALD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('10.08.2026' AS DATE), 'SHARON MCDONALD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 520.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 50.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('11.08.2026' AS DATE), 'SYLVAIN MENARD', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 610.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('12.08.2026' AS DATE), 'PENNY MORRIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 410.33, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('12.08.2026' AS DATE), 'PENNY MORRIS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 341.94, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('12.08.2026' AS DATE), 'STEVEN EDWARDS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 338.04, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('13.08.2026' AS DATE), 'PATRICIA DEWHURST', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 691.52, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.08.2026' AS DATE), 'MELODY LYNN DONALDSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 319.69, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 58.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('13.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 10.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('15.08.2026' AS DATE), 'DIXIE LEE MARTIN PROULX', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 800.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='ART' LIMIT 1)),
(CAST('18.08.2026' AS DATE), 'KRISTIN M ANDERSON', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 450.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('18.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 45.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('19.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 39.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), 'MARY F KUSIOR', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 400.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), 'VERNON HANDLEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 270.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), 'WESLEY HANDLEY', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 595.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 25.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), 'BRIAN PETERS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 901.44, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('20.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 216.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('21.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 35.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('21.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 40.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('21.08.2026' AS DATE), 'RICHARD SEMMENS', (SELECT id FROM urun_tipleri WHERE urun_adi='HALI' LIMIT 1), 550.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),
(CAST('21.08.2026' AS DATE), '', (SELECT id FROM urun_tipleri WHERE urun_adi='DIGER' LIMIT 1), 122.0, 'USD', (SELECT id FROM subeler WHERE sube_adi='OBA' LIMIT 1)),